//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collections.Web.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Collections.Web.Resources.Views.Home.Index_en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        internal static string CreateCollection {
            get {
                return ResourceManager.GetString("CreateCollection", resourceCulture);
            }
        }
        
        internal static string ExploreMore {
            get {
                return ResourceManager.GetString("ExploreMore", resourceCulture);
            }
        }
        
        internal static string CollectionsWithMore {
            get {
                return ResourceManager.GetString("CollectionsWithMore", resourceCulture);
            }
        }
        
        internal static string MostPopularItems {
            get {
                return ResourceManager.GetString("MostPopularItems", resourceCulture);
            }
        }
        
        internal static string LastAddedItems {
            get {
                return ResourceManager.GetString("LastAddedItems", resourceCulture);
            }
        }
        
        internal static string CollectEverything {
            get {
                return ResourceManager.GetString("CollectEverything", resourceCulture);
            }
        }
    }
}
