//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collections.Web.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collections.Web.Resources.Views.Home.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекционируй все что захочешь.
        /// </summary>
        internal static string CollectEverything {
            get {
                return ResourceManager.GetString("CollectEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекции с наибольшим числом экспонатов.
        /// </summary>
        internal static string CollectionsWithMore {
            get {
                return ResourceManager.GetString("CollectionsWithMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать коллекцию.
        /// </summary>
        internal static string CreateCollection {
            get {
                return ResourceManager.GetString("CreateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше коллекций.
        /// </summary>
        internal static string ExploreMore {
            get {
                return ResourceManager.GetString("ExploreMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавно добавленные экспонаты.
        /// </summary>
        internal static string LastAddedItems {
            get {
                return ResourceManager.GetString("LastAddedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярные экспонаты.
        /// </summary>
        internal static string MostPopularItems {
            get {
                return ResourceManager.GetString("MostPopularItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в.
        /// </summary>
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
